
services:
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - inventory-api-data:/var/lib/postgresql/data
