definitions:
  main.Item:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
info:
  contact: {}
paths:
  /inventory:
    get:
      description: Retrieve a list of all items
      parameters:
      - description: 'Pagination: Offset to start the page from'
        in: query
        name: offset
        type: integer
      - description: 'Pagination: Number of items per page'
        in: query
        name: limit
        type: integer
      - description: 'Sorting: A field to sort by'
        in: query
        name: sort
        type: string
      - description: 'Sorting: direction asc or desc'
        in: query
        name: order
        type: string
      - description: 'Filter: search by the part of the name'
        in: query
        name: name
        type: string
      - description: 'Filter: minimum items in stock'
        in: query
        name: min_stock
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all items
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Get a single item by their ID
      parameters:
      - description: Item data
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.Item'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Item'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new item
      tags:
      - items
  /inventory/{id}:
    delete:
      description: Delete item by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete item
      tags:
      - items
    get:
      description: Get a single item by their ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Item'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get item by ID
      tags:
      - items
    patch:
      description: Update all item properties by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: Properties and values to update
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Item'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update all item properties
      tags:
      - items
    put:
      description: Update all item properties by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: Item data
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Item'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update item properties
      tags:
      - items
swagger: "2.0"
